version: '3.8'

services:
  java-app:
    image: petvet-gps:latest
    # container_name: petvet_gps
    # volumes:
    #   - ./app:/app
    working_dir: /app
    command: java -jar petvet-gps-1.0-SNAPSHOT.jar
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
    networks:
      - macvlan_net

networks:
  macvlan_net:
    external: true